version: "3"
services:
  mysql-db:
     image: mysql:8.0
     container_name: mysql
     hostname: mysql
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "weather_db"
       MYSQL_USER: "user"
       MYSQL_PASSWORD: "password"
     ports:
       - "3307:3306"
     volumes:
       - ./data/mysql/:/var/lib/mysql